// Generated by Dartloom. This file is overwritten by project update.
import 'package:dartloom_runtime/dartloom_runtime.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:dartloom_settings/dartloom_settings.dart';
import 'package:dartloom_storage/dartloom_storage.dart';
import 'package:dartloom_logging/dartloom_logging.dart';
import 'dart:io';
import 'package:dartloom_autostart/dartloom_autostart.dart';
import 'package:dartloom_localization/dartloom_localization.dart';
import 'package:mini_todo/l10n/app_localizations.dart';
import 'package:dartloom_resident/dartloom_resident.dart';
import 'package:dartloom_settings_shared_preferences/dartloom_settings_shared_preferences.dart';
import 'package:dartloom_storage_json_file/dartloom_storage_json_file.dart';
import 'package:dartloom_logging_logger/dartloom_logging_logger.dart';
import 'package:dartloom_autostart_launch_at_startup/dartloom_autostart_launch_at_startup.dart';
import 'package:dartloom_localization_gen_l10n/dartloom_localization_gen_l10n.dart';
import 'package:dartloom_resident_tray/dartloom_resident_tray.dart';

Future<void> initializeDartloom({
  Map<String, DartloomFactory> customFactories = const {},
}) async {
  late final Map<String, DartloomFactory> factories;
  final officialFactories = <String, DartloomFactory>{
    'shared_preferences': (_) =>
        DartloomBinding<SettingsStore>(SharedPreferencesSettingsStore()),
    'json_file': (context) async {
      final value = await JsonFileStore.open(
        path: context.options['path'] as String? ?? 'dartloom/data.json',
      );
      return DartloomBinding<JsonStore>(value);
    },
    'logger': (_) => DartloomBinding<AppLogger>(LoggerAppLogger()),
    'launch_at_startup': (context) => DartloomBinding<AutostartService>(
      LaunchAtStartupService(
        appName: context.options['app_name'] as String? ?? "mini_todo",
        appPath:
            context.options['app_path'] as String? ??
            Platform.resolvedExecutable,
        packageName:
            context.options['package_name'] as String? ??
            "com.example.mini_todo",
      ),
    ),
    'gen_l10n': (_) => DartloomBinding<LocalizationService>(
      GenL10nLocalizationService(
        supportedLocales: AppLocalizations.supportedLocales,
        applicationDelegate: AppLocalizations.delegate,
      ),
    ),
    'tray': (context) async {
      final value = TrayResidentService(
        tooltip:
            context.options['tooltip'] as String? ?? 'Dartloom application',
      );
      await value.initialize(
        iconPath: context.options['icon_path'] as String,
        configuration: _dartloomResidentConfiguration(context.options),
      );
      return DartloomBinding<ResidentService>(value, dispose: value.dispose);
    },
  };
  final collisions = officialFactories.keys.toSet().intersection(
    customFactories.keys.toSet(),
  );
  if (collisions.isNotEmpty) {
    throw DartloomException(
      'custom factories cannot replace official factories: $collisions',
    );
  }
  factories = {...officialFactories, ...customFactories};
  await Dartloom.initialize(<DartloomRegistration<Object>>[
    if (_dartloomSupportsCurrentPlatform(const {
      "android",
      "ios",
      "windows",
      "macos",
      "linux",
      "web",
    }))
      DartloomRegistration<SettingsStore>(
        capability: 'settings',
        name: "default",
        factory: "shared_preferences",
        options: <String, Object?>{},
      ),
    if (_dartloomSupportsCurrentPlatform(const {
      "android",
      "ios",
      "windows",
      "macos",
      "linux",
      "web",
    }))
      DartloomRegistration<JsonStore>(
        capability: 'storage',
        name: "json",
        factory: "json_file",
        options: <String, Object?>{"path": "mini_todo/data.json"},
      ),
    if (_dartloomSupportsCurrentPlatform(const {
      "android",
      "ios",
      "windows",
      "macos",
      "linux",
      "web",
    }))
      DartloomRegistration<AppLogger>(
        capability: 'logging',
        name: "default",
        factory: "logger",
        options: <String, Object?>{},
      ),
    if (_dartloomSupportsCurrentPlatform(const {"windows", "macos", "linux"}))
      DartloomRegistration<AutostartService>(
        capability: 'autostart',
        name: "default",
        factory: "launch_at_startup",
        options: <String, Object?>{},
      ),
    if (_dartloomSupportsCurrentPlatform(const {
      "android",
      "ios",
      "windows",
      "macos",
      "linux",
      "web",
    }))
      DartloomRegistration<LocalizationService>(
        capability: 'localization',
        name: "default",
        factory: "gen_l10n",
        options: <String, Object?>{},
      ),
    if (_dartloomSupportsCurrentPlatform(const {"windows", "macos", "linux"}))
      DartloomRegistration<ResidentService>(
        capability: 'resident',
        name: "default",
        factory: "tray",
        options: <String, Object?>{
          "icon_path": "windows/runner/resources/app_icon.ico",
          "tooltip": "Mini Todo",
        },
      ),
  ], factories: factories);
}

Future<void> disposeDartloom() => Dartloom.dispose();

bool _dartloomSupportsCurrentPlatform(Set<String> platforms) {
  final current = kIsWeb
      ? 'web'
      : switch (defaultTargetPlatform) {
          TargetPlatform.android => 'android',
          TargetPlatform.iOS => 'ios',
          TargetPlatform.linux => 'linux',
          TargetPlatform.macOS => 'macos',
          TargetPlatform.windows => 'windows',
          TargetPlatform.fuchsia => 'fuchsia',
        };
  return platforms.contains(current);
}

ResidentConfiguration _dartloomResidentConfiguration(
  Map<String, Object?> options,
) {
  final rawMenu = options['menu'];
  final menu = rawMenu is List
      ? rawMenu
            .map((entry) {
              if (entry is! Map) {
                throw DartloomException('resident menu entries must be maps.');
              }
              if (entry['separator'] == true) {
                return const ResidentMenuItem.separator();
              }
              final id = entry['id'];
              final label = entry['label'];
              if (id is! String || label is! String) {
                throw DartloomException(
                  'resident menu items require string id and label.',
                );
              }
              return ResidentMenuItem.action(
                id: id,
                label: label,
                enabled: entry['enabled'] != false,
              );
            })
            .toList(growable: false)
      : const <ResidentMenuItem>[];
  return ResidentConfiguration(
    menu: menu,
    leftClick: _dartloomResidentClickAction(options['left_click']),
    rightClick: _dartloomResidentClickAction(
      options['right_click'],
      fallback: ResidentClickAction.showMenu,
    ),
    exitMenuItemId: options['exit_menu_item_id'] as String? ?? 'quit',
  );
}

ResidentClickAction _dartloomResidentClickAction(
  Object? value, {
  ResidentClickAction fallback = ResidentClickAction.restore,
}) => switch (value) {
  'menu' => ResidentClickAction.showMenu,
  'ignore' => ResidentClickAction.ignore,
  'restore' => ResidentClickAction.restore,
  _ => fallback,
};

final _dartloomFallbackLocalization = GenL10nLocalizationService(
  supportedLocales: AppLocalizations.supportedLocales,
  applicationDelegate: AppLocalizations.delegate,
);
List<Locale> get dartloomSupportedLocales =>
    Dartloom.contains<LocalizationService>()
    ? Dartloom.get<LocalizationService>().supportedLocales
    : _dartloomFallbackLocalization.supportedLocales;
List<LocalizationsDelegate<dynamic>> get dartloomLocalizationsDelegates =>
    Dartloom.contains<LocalizationService>()
    ? Dartloom.get<LocalizationService>().localizationsDelegates
    : _dartloomFallbackLocalization.localizationsDelegates;
