// Generated by Dartloom. This file is overwritten by project update.
import 'package:dartloom_runtime/dartloom_runtime.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:dartloom_settings/dartloom_settings.dart';
import 'package:dartloom_storage/dartloom_storage.dart';
import 'package:dartloom_logging/dartloom_logging.dart';
import 'dart:io';
import 'package:dartloom_autostart/dartloom_autostart.dart';
import 'package:dartloom_sync/dartloom_sync.dart';
import 'package:dartloom_sync_storage/dartloom_sync_storage.dart';
import 'package:dartloom_sync_flutter/dartloom_sync_flutter.dart';
import 'package:dartloom_sync_workmanager/dartloom_sync_workmanager.dart';
import 'package:dartloom_localization/dartloom_localization.dart';
import 'package:mini_todo/l10n/app_localizations.dart';
import 'package:dartloom_resident/dartloom_resident.dart';
import 'package:dartloom_settings_shared_preferences/dartloom_settings_shared_preferences.dart';
import 'package:dartloom_settings_secure_storage/dartloom_settings_secure_storage.dart';
import 'package:dartloom_storage_json_file/dartloom_storage_json_file.dart';
import 'package:dartloom_logging_logger/dartloom_logging_logger.dart';
import 'package:dartloom_autostart_launch_at_startup/dartloom_autostart_launch_at_startup.dart';
import 'package:dartloom_sync_etag/dartloom_sync_etag.dart';
import 'package:dartloom_sync_webdav/dartloom_sync_webdav.dart';
import 'package:dartloom_localization_gen_l10n/dartloom_localization_gen_l10n.dart';
import 'package:dartloom_resident_tray/dartloom_resident_tray.dart';

Future<void> initializeDartloom({
  Map<String, DartloomFactory> customFactories = const {},
  bool syncWorker = false,
}) async {
  late final Map<String, DartloomFactory> factories;
  final officialFactories = <String, DartloomFactory>{
    'shared_preferences': (_) =>
        DartloomBinding<SettingsStore>(SharedPreferencesSettingsStore()),
    'secure_storage': (_) =>
        const DartloomBinding<SettingsStore>(SecureSettingsStore()),
    'json_file': (context) async {
      final value = await JsonFileStore.open(
        path: context.options['path'] as String? ?? 'dartloom/data.json',
      );
      final syncScope = context.options['sync_scope'] as String?;
      if (syncScope == null) return DartloomBinding<JsonStore>(value);
      final scoped = await ProfileScopedJsonStore.open(
        value,
        context.get<SyncProfileScope>(name: syncScope),
        attachExistingData: context.options['sync_attach_existing'] != false,
      );
      return DartloomBinding<JsonStore>(scoped, dispose: scoped.close);
    },
    'logger': (_) => DartloomBinding<AppLogger>(LoggerAppLogger()),
    'launch_at_startup': (context) => DartloomBinding<AutostartService>(
      LaunchAtStartupService(
        appName: context.options['app_name'] as String? ?? "mini_todo",
        appPath:
            context.options['app_path'] as String? ??
            Platform.resolvedExecutable,
        packageName:
            context.options['package_name'] as String? ??
            "com.example.mini_todo",
      ),
    ),
    'gen_l10n': (_) => DartloomBinding<LocalizationService>(
      GenL10nLocalizationService(
        supportedLocales: AppLocalizations.supportedLocales,
        applicationDelegate: AppLocalizations.delegate,
      ),
    ),
    'tray': (context) async {
      final value = TrayResidentService(
        tooltip:
            context.options['tooltip'] as String? ?? 'Dartloom application',
        linuxIconPath: context.options['icon_path_linux'] as String?,
        macosIconPath: context.options['icon_path_macos'] as String?,
        windowsIconPath: context.options['icon_path_windows'] as String?,
      );
      await value.initialize(
        iconPath: context.options['icon_path'] as String,
        configuration: _dartloomResidentConfiguration(context.options),
      );
      return DartloomBinding<ResidentService>(value, dispose: value.dispose);
    },
    'sync_profile_scope': (context) async {
      final value = await SyncProfileScope.open(
        context.get<SettingsStore>(),
        context.name,
      );
      return DartloomBinding<SyncProfileScope>(value, dispose: value.dispose);
    },
    'etag': (context) async {
      final localStores = <String, ProfileScopedJsonStore>{};
      for (final reference
          in (context.options['stores'] as List).cast<String>()) {
        final name = reference.substring('storage.'.length);
        if (name == 'json') {
          final store = context.get<JsonStore>(name: name);
          if (store is! ProfileScopedJsonStore) {
            throw DartloomException(
              'sync store storage.$name is not profile scoped.',
            );
          }
          localStores[name] = store;
        }
      }
      if (localStores.isEmpty) {
        throw const DartloomException(
          'etag sync currently requires storage.json.',
        );
      }
      final scope = context.get<SyncProfileScope>(name: context.name);
      final profiles = SettingsSyncProfileRepository(
        instanceName: context.name,
        metadata: context.get<SettingsStore>(),
        secretsStore: context.get<SettingsStore>(name: 'sync_secrets'),
        scope: scope,
      );
      final firstStore = localStores.values.first;
      final state = JsonReconciliationStateRepository(
        firstStore.raw,
        instanceName: context.name,
      );
      final backend = WebDavBackendFactory(
        defaultRootPath:
            context.options['backend_root_path'] as String? ?? 'Dartloom',
        connectTimeout: SyncPolicyCodec.parseDuration(
          context.options['backend_connect_timeout'] as String,
        ),
        requestTimeout: SyncPolicyCodec.parseDuration(
          context.options['backend_request_timeout'] as String,
        ),
        maxParallelRequests:
            context.options['backend_max_parallel_requests'] as int,
        createMissingCollections:
            context.options['backend_create_missing_collections'] as bool,
      );
      SyncMergePolicy? merge;
      final mergeFactory = context.options['merge_factory'] as String?;
      if (mergeFactory != null) {
        final factory = factories[mergeFactory];
        if (factory == null) {
          throw DartloomException('missing merge factory $mergeFactory.');
        }
        final binding = await factory(context);
        if (binding.value is! SyncMergePolicy) {
          throw DartloomException(
            'merge factory $mergeFactory must return SyncMergePolicy.',
          );
        }
        merge = binding.value as SyncMergePolicy;
      }
      FlutterSyncRuntimeSignals? runtime;
      if (!syncWorker) {
        runtime = FlutterSyncRuntimeSignals();
        await runtime.start();
      }
      final coordinator = SyncCoordinator(
        instanceName: context.name,
        policy: SyncPolicyCodec.resolve(
          (context.options['policy'] as Map).cast<String, Object?>(),
          _dartloomCurrentPlatform,
        ),
        profiles: profiles,
        localFactory: JsonLocalReplicaFactory(localStores),
        stateRepository: state,
        reconciler: const EtagReconciler(),
        backends: {'webdav': backend},
        runtimeSignals: runtime,
        backgroundScheduler: syncWorker
            ? null
            : WorkmanagerSyncBackgroundScheduler(
                callbackDispatcher: dartloomSyncCallbackDispatcher,
              ),
        merge: merge,
      );
      await coordinator.start();
      return DartloomBinding<SyncService>(
        coordinator,
        dispose: () async {
          await coordinator.dispose();
          await runtime?.dispose();
        },
      );
    },
  };
  final collisions = officialFactories.keys.toSet().intersection(
    customFactories.keys.toSet(),
  );
  if (collisions.isNotEmpty) {
    throw DartloomException(
      'custom factories cannot replace official factories: $collisions',
    );
  }
  factories = {...officialFactories, ...customFactories};
  await Dartloom.initialize(<DartloomRegistration<Object>>[
    if (_dartloomSupportsCurrentPlatform(const {
      "android",
      "ios",
      "windows",
      "macos",
      "linux",
      "web",
    }))
      DartloomRegistration<SyncProfileScope>(
        capability: 'sync_profile',
        name: "default",
        factory: 'sync_profile_scope',
        dependsOn: const [DartloomReference('settings', 'default')],
      ),
    if ((!syncWorker || true) &&
        _dartloomSupportsCurrentPlatform(const {
          "android",
          "ios",
          "windows",
          "macos",
          "linux",
          "web",
        }))
      DartloomRegistration<SettingsStore>(
        capability: 'settings',
        name: "default",
        factory: "shared_preferences",
        options: <String, Object?>{},
      ),
    if ((!syncWorker || true) &&
        _dartloomSupportsCurrentPlatform(const {
          "android",
          "ios",
          "windows",
          "macos",
          "linux",
          "web",
        }))
      DartloomRegistration<SettingsStore>(
        capability: 'settings',
        name: "sync_secrets",
        factory: "secure_storage",
        options: <String, Object?>{},
      ),
    if ((!syncWorker || true) &&
        _dartloomSupportsCurrentPlatform(const {
          "android",
          "ios",
          "windows",
          "macos",
          "linux",
          "web",
        }))
      DartloomRegistration<JsonStore>(
        capability: 'storage',
        name: "json",
        factory: "json_file",
        options: <String, Object?>{
          "path": "mini_todo/data.json",
          "sync_scope": "default",
          "sync_attach_existing": true,
        },
        dependsOn: const [DartloomReference('sync_profile', 'default')],
      ),
    if ((!syncWorker || false) &&
        _dartloomSupportsCurrentPlatform(const {
          "android",
          "ios",
          "windows",
          "macos",
          "linux",
          "web",
        }))
      DartloomRegistration<AppLogger>(
        capability: 'logging',
        name: "default",
        factory: "logger",
        options: <String, Object?>{},
      ),
    if ((!syncWorker || false) &&
        _dartloomSupportsCurrentPlatform(const {"windows", "macos", "linux"}))
      DartloomRegistration<AutostartService>(
        capability: 'autostart',
        name: "default",
        factory: "launch_at_startup",
        options: <String, Object?>{},
      ),
    if ((!syncWorker || true) &&
        _dartloomSupportsCurrentPlatform(const {
          "android",
          "ios",
          "windows",
          "macos",
          "linux",
          "web",
        }))
      DartloomRegistration<SyncService>(
        capability: 'sync',
        name: "default",
        factory: "etag",
        options: <String, Object?>{
          "stores": ["storage.json"],
          "policy": <String, Object?>{
            "mode": "automatic",
            "triggers": <String, Object?>{
              "startup": true,
              "resume": true,
              "connectivity_restored": true,
              "local_write": <String, Object?>{
                "enabled": true,
                "debounce": "2s",
                "max_delay": "10s",
              },
            },
            "discovery": <String, Object?>{
              "remote_changes": "auto",
              "poll_interval": "5m",
              "safety_reconcile_interval": "15m",
            },
            "execution": <String, Object?>{
              "timeout": "2m",
              "busy_behavior": "coalesce_then_rerun",
              "max_parallel_transfers": 4,
              "max_object_size": "20mb",
            },
            "retry": <String, Object?>{
              "strategy": "exponential",
              "initial_delay": "5s",
              "fixed_delay": "30s",
              "sequence": ["5s", "30s", "2m", "10m"],
              "multiplier": 3,
              "max_delay": "10m",
              "jitter": "20%",
              "max_attempts": 0,
            },
            "conflicts": <String, Object?>{
              "strategy": "preserve",
              "delete_vs_update": "conflict",
            },
            "state": <String, Object?>{
              "base_payload": "always",
              "tombstone_retention": "30d",
            },
            "profiles": <String, Object?>{
              "sync_on_activate": true,
              "existing_data": "attach_to_default",
            },
            "platforms": <String, Object?>{
              "android": <String, Object?>{
                "discovery": <String, Object?>{"poll_interval": "5m"},
                "background": <String, Object?>{
                  "enabled": true,
                  "enqueue_on_pending": true,
                  "periodic_interval": "15m",
                  "flex_interval": "5m",
                  "network": "connected",
                  "requires_battery_not_low": true,
                  "requires_charging": false,
                  "timeout": "2m",
                },
              },
              "windows": <String, Object?>{
                "discovery": <String, Object?>{"poll_interval": "5m"},
              },
              "macos": <String, Object?>{
                "discovery": <String, Object?>{"poll_interval": "5m"},
              },
              "linux": <String, Object?>{
                "discovery": <String, Object?>{"poll_interval": "5m"},
              },
            },
          },
          "backend_root_path": "MiniTodo",
          "backend_connect_timeout": "10s",
          "backend_request_timeout": "30s",
          "backend_max_parallel_requests": 4,
          "backend_create_missing_collections": true,
        },
        dependsOn: const [
          DartloomReference('storage', 'json'),
          DartloomReference('sync_profile', 'default'),
          DartloomReference('settings', 'default'),
          DartloomReference('settings', 'sync_secrets'),
        ],
      ),
    if ((!syncWorker || false) &&
        _dartloomSupportsCurrentPlatform(const {
          "android",
          "ios",
          "windows",
          "macos",
          "linux",
          "web",
        }))
      DartloomRegistration<LocalizationService>(
        capability: 'localization',
        name: "default",
        factory: "gen_l10n",
        options: <String, Object?>{},
      ),
    if ((!syncWorker || false) &&
        _dartloomSupportsCurrentPlatform(const {"windows", "macos", "linux"}))
      DartloomRegistration<ResidentService>(
        capability: 'resident',
        name: "default",
        factory: "tray",
        options: <String, Object?>{
          "icon_path": "windows/runner/resources/app_icon.ico",
          "icon_path_linux": "assets/tray_icon.png",
          "tooltip": "Mini Todo",
        },
      ),
  ], factories: factories);
}

Future<void> disposeDartloom() => Dartloom.dispose();

@pragma('vm:entry-point')
void dartloomSyncCallbackDispatcher() {
  executeDartloomSyncWorker((instanceName) async {
    await initializeDartloom(syncWorker: true);
    try {
      final service = Dartloom.get<SyncService>(name: instanceName);
      return (await service.syncNow()).isSuccess;
    } finally {
      await disposeDartloom();
    }
  });
}

String get _dartloomCurrentPlatform => kIsWeb
    ? 'web'
    : switch (defaultTargetPlatform) {
        TargetPlatform.android => 'android',
        TargetPlatform.iOS => 'ios',
        TargetPlatform.linux => 'linux',
        TargetPlatform.macOS => 'macos',
        TargetPlatform.windows => 'windows',
        TargetPlatform.fuchsia => 'fuchsia',
      };

bool _dartloomSupportsCurrentPlatform(Set<String> platforms) {
  return platforms.contains(_dartloomCurrentPlatform);
}

ResidentConfiguration _dartloomResidentConfiguration(
  Map<String, Object?> options,
) {
  final rawMenu = options['menu'];
  final menu = rawMenu is List
      ? rawMenu
            .map((entry) {
              if (entry is! Map) {
                throw DartloomException('resident menu entries must be maps.');
              }
              if (entry['separator'] == true) {
                return const ResidentMenuItem.separator();
              }
              final id = entry['id'];
              final label = entry['label'];
              if (id is! String || label is! String) {
                throw DartloomException(
                  'resident menu items require string id and label.',
                );
              }
              return ResidentMenuItem.action(
                id: id,
                label: label,
                enabled: entry['enabled'] != false,
              );
            })
            .toList(growable: false)
      : const <ResidentMenuItem>[];
  return ResidentConfiguration(
    menu: menu,
    leftClick: _dartloomResidentClickAction(options['left_click']),
    rightClick: _dartloomResidentClickAction(
      options['right_click'],
      fallback: ResidentClickAction.showMenu,
    ),
    exitMenuItemId: options['exit_menu_item_id'] as String? ?? 'quit',
  );
}

ResidentClickAction _dartloomResidentClickAction(
  Object? value, {
  ResidentClickAction fallback = ResidentClickAction.restore,
}) => switch (value) {
  'menu' => ResidentClickAction.showMenu,
  'ignore' => ResidentClickAction.ignore,
  'restore' => ResidentClickAction.restore,
  _ => fallback,
};

final _dartloomFallbackLocalization = GenL10nLocalizationService(
  supportedLocales: AppLocalizations.supportedLocales,
  applicationDelegate: AppLocalizations.delegate,
);
List<Locale> get dartloomSupportedLocales =>
    Dartloom.contains<LocalizationService>()
    ? Dartloom.get<LocalizationService>().supportedLocales
    : _dartloomFallbackLocalization.supportedLocales;
List<LocalizationsDelegate<dynamic>> get dartloomLocalizationsDelegates =>
    Dartloom.contains<LocalizationService>()
    ? Dartloom.get<LocalizationService>().localizationsDelegates
    : _dartloomFallbackLocalization.localizationsDelegates;
